config/routes.rb
Moviez::Application.routes.draw do
  root :to => 'welcome#index'
  get '/movies/search' => 'movies#search', as: 'movies_search'
  get '/movies/new/search' => 'movies#new_search', as: 'new_movies_search'
  post '/movies' => 'movies#create', as: 'add_new_movie'
  post '/movies/:id' => 'movies#edit', as: 'edit_movie'
  resources :movies
  resources :actors

#     movies GET    /movies(.:format)          movies#index
#            POST   /movies(.:format)          movies#create
#  new_movie GET    /movies/new(.:format)      movies#new
# edit_movie GET    /movies/:id/edit(.:format) movies#edit
#      movie GET    /movies/:id(.:format)      movies#show
#            PUT    /movies/:id(.:format)      movies#update
#            DELETE /movies/:id(.:format)      movies#destroy
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_and_belongs_to_many :movies
  attr_accessible :name
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :actors
  attr_accessible :title, :year, :plot, :mpaa_rating, :rating, :poster
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def search
    @movies = Movie.where(title: params[:title])
    render "index"
  end

  def index
    if params[:title]
      @movies = Movie.where(title: params[:title])
    else
      @movies = Movie.all
    end
  end

  def new_search
    @movies = Imdb::Search.new(params[:title]).movies[0..9]
    render "new"
  end

  def new
    if params[:title]
      @movies = Imdb::Search.new(params[:title]).movies[0..9]
    else
      @movies = nil
    end
  end

  def create
    new_movie = Imdb::Search.new(params[:title]).movies.first
    movie = Movie.new
    movie.title = new_movie.title
    movie.year = new_movie.year
    movie.plot = new_movie.plot
    movie.mpaa_rating = new_movie.mpaa_rating
    if params[:rating]
      movie.rating = params[:rating]
    end
    movie.poster = new_movie.poster
    new_movie.cast_members.each do |cast_member|
      if Actor.where(name: cast_member) == []
        actor = Actor.new(name: cast_member)
        actor.save
        movie.actors << actor
      else
        actor = Actor.where(name: cast_member)
        movie.actors << actor
      end
    end
    movie.save
    redirect_to "/movies"
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
    case params[:rating]
    when "favorite"
      @movie.rating = 100
    when "up"
      @movie.rating += 1
    when "down"
      @movie.rating -= 1
    end
    @movie.save
    render "show"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def movie_length_hours(movie)
    # number of whole hours in movie length
    hours = movie.length / 60
  end

  def movie_length_minutes(movie)
    # number of minutes left over in movie length
    hours = movie.length % 60
  end
end

app/views/actors/index.html.erb
<ul>
  <% @actors.each do |actor| %>
    <li>
      <a href="/actors/<%= actor.id %>">
        <%= actor.name %>
      </a>
    </li>
  <% end %>
</ul>

app/views/actors/new.html.erb
<h1>Add a new actor</h1>
<form action="/actors" method="post">
  <label for="name">Enter a name</label><br/>
  <input type="string" name="name" autofocus="true">
  <button>Submit</button>
</form>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>
<ul>
  <% @actor.movies.each do |movie| %>
    <li>
      <a href="/movies/<%= movie.id %>">
        <%= movie.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/application/_navbar.html.erb
<a href="/movies">See Movies</a>
<a href="/movies/new">Add a new movie</a>
<a href="/actors/new">Add a new actor</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviez</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'navbar' %>
<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<h1>Check out these saved movies!</h1>

<form action="/movies" method="get">
  <label for="title">Search by movie title</label><br/>
  <input type="string" name="title">
  <button>Search</button>
</form>

<ul>
  <% @movies.each do |movie| %>
    <li>
      <a href="/movies/<%= movie.id %>">
        <%= movie.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>Add a new movie!</h1>

<form action="/movies/new" method="get">
  <label for="title">Search by movie title</label><br/>
  <input type="string" name="title">
  <button>Search</button>
</form>

<% unless @movies.nil? %>
<ol>
  <% @movies.each do |movie| %>
    <li>
      <h3><%= movie.title %></h3>
        <ul>
          <li>Year: <%= movie.year %></li>
          <li>Plot: <%= truncate(movie.plot, length: 50) %></li>
          <li>MPAA Rating: <%= movie.mpaa_rating %></li>
          <li>Length: <%= pluralize(movie_length_hours(movie), 'hour') %> and <%= pluralize(movie_length_minutes(movie), 'minute') %></li>
        </ul>
      <%= button_to "Save this movie", add_new_movie_path(title: movie.title) %>
      <%= button_to "Favorite this movie", add_new_movie_path(title: movie.title, rating: 100) %>
    </li>
  <% end %>
</ol>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<img src="<%= @movie.poster %>" width=300>
<ul>
  <li>Year: <%= @movie.year %></li>
  <li>Plot: <%= @movie.plot %></li>
  <li>MPAA Rating: <%= @movie.mpaa_rating %></li>
  <li>Rating: <%= number_to_percentage(@movie.rating, precision: 0) %><%= button_to "+1", edit_movie_path(rating: "up") %><%= button_to "-1", edit_movie_path(rating: "down") %><%= button_to "Favorite this movie", edit_movie_path(rating: "favorite") %></li>
  <li>Cast:
    <ul>
      <% @movie.actors.each do |actor| %>
        <li><a href="/actors/<%= actor.id %>"><%= actor.name %></a></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>